#!/usr/bin/env bash
# Summary: Show the current Julia version and its origin
#
# Shows the currently selected Julia version and how it was
# selected. To obtain only the version string, use `jlenv
# version-name'.

set -e
[ -n "$JLENV_DEBUG" ] && set -x

echo "$(jlenv-version-name) (set by $(jlenv-version-origin))"
