#!/usr/bin/env bash
# Usage: jlenv completions <command> [arg1 arg2...]

set -e
[ -n "$JLENV_DEBUG" ] && set -x

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  jlenv-help --usage completions >&2
  exit 1
fi

# Provide jlenv completions
if [ "$COMMAND" = "--complete" ]; then
  exec jlenv-commands
fi

COMMAND_PATH="$(command -v "jlenv-$COMMAND" || command -v "jlenv-sh-$COMMAND")"

# --help is provided automatically
echo --help

if grep -iE "^([#%]|--|//) provide jlenv completions" "$COMMAND_PATH" >/dev/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi
