#!/usr/bin/env bash
set -e
unset CDPATH

if [ "$1" = "--debug" ]; then
  export JLENV_DEBUG=1
  shift
fi

if [ -n "$JLENV_DEBUG" ]; then
  export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
  set -x
fi

abort() {
  { if [ "$#" -eq 0 ]; then cat -
    else echo "jlenv: $*"
    fi
  } >&2
  exit 1
}

if enable -f "${BASH_SOURCE%/*}"/../libexec/jlenv-realpath.dylib realpath 2>/dev/null; then
  abs_dirname() {
    local path="$(realpath "$1")"
    echo "${path%/*}"
  }
else
  [ -z "$JLENV_NATIVE_EXT" ] || abort "failed to load \`realpath' builtin"

  READLINK=$(type -p greadlink readlink | head -1)
  [ -n "$READLINK" ] || abort "cannot find readlink - are you missing GNU coreutils?"

  resolve_link() {
    $READLINK "$1"
  }

  abs_dirname() {
    local cwd="$PWD"
    local path="$1"

    while [ -n "$path" ]; do
      cd "${path%/*}"
      local name="${path##*/}"
      path="$(resolve_link "$name" || true)"
    done

    pwd
    cd "$cwd"
  }
fi

if [ -z "${JLENV_ROOT}" ]; then
  JLENV_ROOT="${HOME}/.jlenv"
else
  JLENV_ROOT="${JLENV_ROOT%/}"
fi
export JLENV_ROOT

if [ -z "${JLENV_DIR}" ]; then
  JLENV_DIR="$PWD"
else
  cd "$JLENV_DIR" 2>/dev/null || abort "cannot change working directory to \`$JLENV_DIR'"
  JLENV_DIR="$PWD"
  cd "$OLDPWD"
fi
export JLENV_DIR


shopt -s nullglob

bin_path="$(abs_dirname "$0")"
for plugin_bin in "${JLENV_ROOT}/plugins/"*/bin; do
  PATH="${plugin_bin}:${PATH}"
done
export PATH="${bin_path}:${PATH}"

JLENV_HOOK_PATH="${JLENV_HOOK_PATH}:${JLENV_ROOT}/jlenv.d"
if [ "${bin_path%/*}" != "$JLENV_ROOT" ]; then
  # Add jlenv's own `jlenv.d` unless jlenv was cloned to JLENV_ROOT
  JLENV_HOOK_PATH="${JLENV_HOOK_PATH}:${bin_path%/*}/jlenv.d"
fi
JLENV_HOOK_PATH="${JLENV_HOOK_PATH}:/usr/local/etc/jlenv.d:/etc/jlenv.d:/usr/lib/jlenv/hooks"
for plugin_hook in "${JLENV_ROOT}/plugins/"*/etc/jlenv.d; do
  JLENV_HOOK_PATH="${JLENV_HOOK_PATH}:${plugin_hook}"
done
JLENV_HOOK_PATH="${JLENV_HOOK_PATH#:}"
export JLENV_HOOK_PATH

shopt -u nullglob


command="$1"
case "$command" in
"" )
  { jlenv---version
    jlenv-help
  } | abort
  ;;
-v | --version )
  exec jlenv---version
  ;;
-h | --help )
  exec jlenv-help
  ;;
* )
  command_path="$(command -v "jlenv-$command" || true)"
  [ -n "$command_path" ] || abort "no such command \`$command'"

  shift 1
  if [ "$1" = --help ]; then
    if [[ "$command" == "sh-"* ]]; then
      echo "jlenv help \"$command\""
    else
      exec jlenv-help "$command"
    fi
  else
    exec "$command_path" "$@"
  fi
  ;;
esac
